#macro GOOD 0
#macro BAD 1
#macro NEUTRAL 2

#macro MAX_SYNC 6
#macro MAX_CHAOS 6
#macro ITEM_SPEED 6
#macro ITEM_FREQUENCY 80

#macro AMBIENT_INDUSTRIAL_GAIN 0.1
#macro MAIN_MUSIC_GAIN 0.7
#macro WIN_MUSIC_GAIN 0.7
#macro DESYNC_GAIN 1